Html based Ver 1.0.4
Microsoft/PowerBI-visuals-forcasting-exp pull request #10
Opened 2018-04-24 15:20 UTC by boefraty74

2018-04-25 15:07 UTC, ignatvilesov requested changes
Please also fix all of TSLint issues reported by Travis CI

https://travis-ci.org/Microsoft/PowerBI-visuals-forcasting-exp/builds/370931675?utm_source=github_status&utm_medium=notification

2018-04-25 15:07 UTC, ignatvilesov commented on package.json
> +    "postinstall": "pbiviz update 1.10.0",
Please remove `package-lock.json` from git

2018-04-25 15:07 UTC, ignatvilesov commented on package.json
> +    "powerbi-visuals-tools": "1.10.0"
As you use powerbi-visuals-utils-dataview-tuils you would need to add `"powerbi-visuals-utils-dataviewutils": "1.2.0"` as well.

2018-04-26 08:41 UTC, boefraty74 commented on package.json
> +    "postinstall": "pbiviz update 1.10.0",
done

2018-04-26 09:07 UTC, ignatvilesov approved these changes

2018-04-26 09:09 UTC, merged